# Linear Algebra

## basic

scalar $a$

vector $\textbf{a}$

matrix $\textbf{A} \in \R ^{m\times n}$

tensor **A**


In [2]:
import numpy as np


## multiplying

$ \textbf{C}= \textbf{A} \textbf{B} $ is defined by $ \textbf{C}_{i,j} = \sum_{k} \textbf{A}_{i,k} \textbf{B}_{k,j}$

In [11]:
A = np.array([[1, 2], [3,4]])
B = np.array([[5, 6], [7, 8]])
C = A.dot(B)
print('A',A)
print('B',B)
print('C',C)

A [[1 2]
 [3 4]]
B [[5 6]
 [7 8]]
C [[19 22]
 [43 50]]


$\textbf{C} = \textbf{A} \odot \textbf{B} $ is the element-wise/hadamard product 

In [10]:
C_hadamard = np.multiply(A,B)
print(C_hadamard)

[[ 5 12]
 [21 32]]


## inverse
$ \textbf{A}^{-1} \textbf{A} = \textbf{I}_{n}$

when $\textbf{A} x = b $, $x = \textbf{A}^{-1}b$

In [14]:
A_inv = np.linalg.inv(A)
print(A_inv)

I = A_inv.dot(A)
print(I)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]


## norm
$L^{p} = \| x \| _{p} = (\sum_{i}|x_{i}|^{p})^{\frac{1}{p}}$

In [18]:
v = np.array([1,2,3,4])
L2 = np.linalg.norm(v)
print(L2)

5.477225575051661


## eigendecomposition
When $\textbf{A}$ is a square matrix, 

$\textbf{v}$ is the right eigen vector, $\lambda$ is the eigenvalue if

$$\textbf{A} \textbf{v} = \lambda \textbf{v}$$ 

$\textbf{v}$ is a left eigen vector if

$$\textbf{v}^{T} \textbf{A} = \lambda \textbf{v}^{T}$$

Then the eigendecomposition of $\textbf{A}$ is

$$ \textbf{A} = \textbf{V} diag(\lambda) \textbf{V}^{-1}$$

When $\textbf{A}$ is a real symmetric matrix, it is guaranteed to have

$$ \textbf{A} = \textbf{Q} \Lambda \textbf{Q}^{T}$$

where $\textbf{Q}$ is an orthogonal matrix and $\Lambda$ is a diagonal matrix

In [25]:
eigen_value, eigen_vector = np.linalg.eig(A)
print(eigen_value)
print(eigen_vector)

A_deco = eigen_vector.dot(np.diag(eigen_value)).dot(np.linalg.inv(eigen_vector))
print(A)
print(A_deco)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[[1 2]
 [3 4]]
[[1. 2.]
 [3. 4.]]


## single value decomposition
when $\textbf{A}$ is not a square matrix, SVG is
$$ \textbf{A} = \textbf{U} \textbf{D} \textbf{V}^{T} $$
where left-singular vector $\textbf{U}$ and right-singular vector $\textbf{V}$ are orthogonal, singular-values $\textbf{D}$ is diagonal

In [49]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
u,d,v = np.linalg.svd(A)
print(A)
print(u)
print(d)
diag = np.zeros((2,3),float)
np.fill_diagonal(diag,d)
print(diag)
print(v)
A_deco = u.dot(diag).dot(v)
print(A_deco)

[[1 2 3]
 [4 5 6]]
[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
[9.508032   0.77286964]
[[9.508032   0.         0.        ]
 [0.         0.77286964 0.        ]]
[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]
[[1. 2. 3.]
 [4. 5. 6.]]


## trace
$Tr(\textbf{A}) = \sum_{i} \textbf{A}_{i,i}$

In [54]:
tr = np.trace(A)
print(A)
print(tr)
f = np.sqrt(np.trace(A.dot(A.T)))
print(f)
print(np.linalg.norm(A))

[[1 2 3]
 [4 5 6]]
6
9.539392014169456
9.539392014169456


## determinant
