In [8]:
import torch
import torch.nn.functional as F

def softmax_one(x, dim):
    x = x - x.max(dim=dim, keepdim=True).values
    exp_x = torch.exp(x)
    return exp_x / (1 + exp_x.sum(dim=dim, keepdim=True))

softmax = F.softmax


In [10]:
scores = torch.FloatTensor([ 0.4202, -2.1783,  1.0923,  1.0282,  1.6933, -0.2471,  0.2865, -0.2099,
         1.6876,  0.8158,  0.8784, -0.8089,  0.9769, -0.6090, -1.2419,  1.1895,
         0.0505,  2.3182, -0.1766, -0.5399,  0.1346, -0.0824,  1.1482,  1.0165,
         0.9373, -0.0946, -0.3365,  1.2053,  0.4422, -0.5857, -2.3086, -1.1120])

print(scores)
print(F.softmax(scores, dim=-1))
print(softmax_one(scores, dim=-1))


tensor([ 0.4202, -2.1783,  1.0923,  1.0282,  1.6933, -0.2471,  0.2865, -0.2099,
         1.6876,  0.8158,  0.8784, -0.8089,  0.9769, -0.6090, -1.2419,  1.1895,
         0.0505,  2.3182, -0.1766, -0.5399,  0.1346, -0.0824,  1.1482,  1.0165,
         0.9373, -0.0946, -0.3365,  1.2053,  0.4422, -0.5857, -2.3086, -1.1120])
tensor([0.0239, 0.0018, 0.0468, 0.0439, 0.0853, 0.0123, 0.0209, 0.0127, 0.0848,
        0.0355, 0.0378, 0.0070, 0.0417, 0.0085, 0.0045, 0.0515, 0.0165, 0.1594,
        0.0132, 0.0091, 0.0180, 0.0144, 0.0495, 0.0434, 0.0401, 0.0143, 0.0112,
        0.0524, 0.0244, 0.0087, 0.0016, 0.0052])
tensor([0.0206, 0.0015, 0.0403, 0.0378, 0.0736, 0.0106, 0.0180, 0.0110, 0.0732,
        0.0306, 0.0326, 0.0060, 0.0359, 0.0074, 0.0039, 0.0445, 0.0142, 0.1375,
        0.0113, 0.0079, 0.0155, 0.0125, 0.0427, 0.0374, 0.0346, 0.0123, 0.0097,
        0.0452, 0.0211, 0.0075, 0.0013, 0.0045])


In [9]:
import math

scores = torch.FloatTensor([-math.inf, -math.inf,  1.0923,  1.0282,  1.6933, -0.2471,  0.2865, -0.2099,
         1.6876,  0.8158,  0.8784, -0.8089,  0.9769, -0.6090, -1.2419,  1.1895,
         0.0505,  2.3182, -0.1766, -0.5399,  0.1346, -0.0824,  1.1482,  1.0165,
         0.9373, -0.0946, -0.3365,  1.2053,  0.4422, -0.5857, -2.3086, -1.1120])

print(scores)
print(F.softmax(scores, dim=-1))
print(softmax_one(scores, dim=-1))


tensor([   -inf,    -inf,  1.0923,  1.0282,  1.6933, -0.2471,  0.2865, -0.2099,
         1.6876,  0.8158,  0.8784, -0.8089,  0.9769, -0.6090, -1.2419,  1.1895,
         0.0505,  2.3182, -0.1766, -0.5399,  0.1346, -0.0824,  1.1482,  1.0165,
         0.9373, -0.0946, -0.3365,  1.2053,  0.4422, -0.5857, -2.3086, -1.1120])
tensor([0.0000, 0.0000, 0.0480, 0.0450, 0.0876, 0.0126, 0.0214, 0.0131, 0.0871,
        0.0364, 0.0388, 0.0072, 0.0428, 0.0088, 0.0047, 0.0529, 0.0169, 0.1636,
        0.0135, 0.0094, 0.0184, 0.0148, 0.0508, 0.0445, 0.0411, 0.0146, 0.0115,
        0.0537, 0.0251, 0.0090, 0.0016, 0.0053])
tensor([0.0000, 0.0000, 0.0413, 0.0387, 0.0753, 0.0108, 0.0184, 0.0112, 0.0748,
        0.0313, 0.0333, 0.0062, 0.0368, 0.0075, 0.0040, 0.0455, 0.0146, 0.1406,
        0.0116, 0.0081, 0.0158, 0.0127, 0.0436, 0.0382, 0.0353, 0.0126, 0.0099,
        0.0462, 0.0215, 0.0077, 0.0014, 0.0046])


In [17]:
scores = torch.randn((4,4))
print(scores)
mask = torch.full((4,4), float("-inf"))
mask = torch.triu(mask, diagonal=1)
scores = scores + mask
print(scores)
print(F.softmax(scores, dim=-1))
print(softmax_one(scores, dim=-1))

tensor([[ 0.1995, -0.6570, -0.1939, -1.8112],
        [ 1.1814,  0.3016, -0.3195,  0.7096],
        [ 1.2462, -2.5478,  0.7005,  0.9153],
        [-0.7719,  0.0729, -0.1832,  0.0173]])
tensor([[ 0.1995,    -inf,    -inf,    -inf],
        [ 1.1814,  0.3016,    -inf,    -inf],
        [ 1.2462, -2.5478,  0.7005,    -inf],
        [-0.7719,  0.0729, -0.1832,  0.0173]])
tensor([[1.0000, 0.0000, 0.0000, 0.0000],
        [0.7068, 0.2932, 0.0000, 0.0000],
        [0.6242, 0.0140, 0.3617, 0.0000],
        [0.1364, 0.3175, 0.2458, 0.3003]])
tensor([[0.5000, 0.0000, 0.0000, 0.0000],
        [0.4141, 0.1718, 0.0000, 0.0000],
        [0.3843, 0.0086, 0.2227, 0.0000],
        [0.1035, 0.2410, 0.1865, 0.2279]])
